name: "Side-by-Side Blueprint Action"
description: "Complete CI solution for Lean 4 projects with Side-by-Side Blueprint documentation"
author: "e-vergo"

branding:
  icon: "book-open"
  color: "blue"

inputs:
  project-directory:
    description: "Directory containing lakefile.toml and runway.json"
    required: false
    default: "."

  lean-version:
    description: "Override Lean version (auto-detected from lean-toolchain by default)"
    required: false
    default: ""

  docgen4-mode:
    description: "DocGen4 mode: skip, docs-static, or generate"
    required: false
    default: "skip"

  deploy-pages:
    description: "Upload artifact for GitHub Pages deployment"
    required: false
    default: "true"

outputs:
  site-path:
    description: "Path to generated site directory"
    value: ${{ steps.generate-site.outputs.site-path }}

  paper-pdf-path:
    description: "Path to generated paper PDF (if paper.tex configured)"
    value: ${{ steps.generate-paper.outputs.pdf-path }}

runs:
  using: "composite"
  steps:
    # ========================================
    # STEP 1: Free disk space
    # ========================================
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.0
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false

    # ========================================
    # STEP 2: Checkout toolchain repos
    # ========================================
    - name: Checkout SubVerso
      uses: actions/checkout@v4
      with:
        repository: e-vergo/subverso
        path: _sbs_toolchain/subverso
        ref: main

    - name: Checkout LeanArchitect
      uses: actions/checkout@v4
      with:
        repository: e-vergo/LeanArchitect
        path: _sbs_toolchain/LeanArchitect
        ref: main

    - name: Checkout Dress
      uses: actions/checkout@v4
      with:
        repository: e-vergo/Dress
        path: _sbs_toolchain/Dress
        ref: main

    - name: Checkout Runway
      uses: actions/checkout@v4
      with:
        repository: e-vergo/Runway
        path: _sbs_toolchain/Runway
        ref: main

    - name: Checkout dress-blueprint-action (for assets)
      uses: actions/checkout@v4
      with:
        repository: e-vergo/dress-blueprint-action
        path: _sbs_toolchain/dress-blueprint-action
        ref: main

    # ========================================
    # STEP 3: Install elan
    # ========================================
    - name: Install elan
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    # ========================================
    # STEP 4: Install Lean toolchain
    # ========================================
    - name: Install Lean toolchain
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        source $HOME/.elan/env
        if [ -n "${{ inputs.lean-version }}" ]; then
          echo "Installing specified Lean version: ${{ inputs.lean-version }}"
          elan toolchain install ${{ inputs.lean-version }}
          elan default ${{ inputs.lean-version }}
        fi
        echo "Verifying Lean installation..."
        lake --version

    # ========================================
    # STEP 5: Install LaTeX
    # ========================================
    - name: Install LaTeX
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-science

    # ========================================
    # STEP 6: Fetch mathlib cache from server
    # ========================================
    - name: Fetch mathlib cache
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "Fetching mathlib cache from server..."
        lake exe cache get || echo "::warning::Server cache unavailable, will build from source"
        OLEAN_COUNT=$(find .lake/packages/mathlib -name "*.olean" 2>/dev/null | wc -l)
        echo "Found $OLEAN_COUNT oleans from mathlib cache"

    # ========================================
    # STEP 7: Build toolchain
    # ========================================
    - name: Build SubVerso
      shell: bash
      working-directory: ${{ github.workspace }}/_sbs_toolchain/subverso
      run: |
        echo "Building SubVerso (highlighting extraction)..."
        lake build
        echo "SubVerso build complete"

    - name: Build LeanArchitect
      shell: bash
      working-directory: ${{ github.workspace }}/_sbs_toolchain/LeanArchitect
      run: |
        echo "Building LeanArchitect (@[blueprint] attribute)..."
        lake build
        echo "LeanArchitect build complete"

    - name: Build Dress
      shell: bash
      working-directory: ${{ github.workspace }}/_sbs_toolchain/Dress
      run: |
        echo "Building Dress (artifact generation)..."
        lake build
        echo "Dress build complete"

    - name: Build Runway
      shell: bash
      working-directory: ${{ github.workspace }}/_sbs_toolchain/Runway
      run: |
        echo "Building Runway (site generator)..."
        lake build
        echo "Runway build complete"

    # ========================================
    # STEP 8: Build project with Dress
    # ========================================
    - name: Build project with Dress artifacts
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "Building project with Dress artifact generation..."
        mkdir -p .lake/build
        echo "1" > .lake/build/.dress
        lake build
        rm -f .lake/build/.dress

        # Verify dressed artifacts were generated
        DRESSED_COUNT=$(find .lake/build/dressed -name "*.html" 2>/dev/null | wc -l)
        echo "Generated $DRESSED_COUNT dressed HTML artifacts"
        if [ "$DRESSED_COUNT" -eq 0 ]; then
          echo "::warning::No dressed artifacts found - check @[blueprint] attributes"
        fi

    # ========================================
    # STEP 9: Build blueprint facet
    # ========================================
    - name: Build blueprint facet
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "Building blueprint Lake facet..."
        lake build :blueprint
        echo "Blueprint facet complete"

    # ========================================
    # STEP 10: Generate dependency graph
    # ========================================
    - name: Generate dependency graph
      id: generate-graph
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "Extracting projectName from runway.json..."
        if [ ! -f "runway.json" ]; then
          echo "::error::runway.json not found in ${{ inputs.project-directory }}"
          exit 1
        fi

        # Extract projectName using grep/sed (no jq dependency)
        PROJECT_NAME=$(grep -o '"projectName"[[:space:]]*:[[:space:]]*"[^"]*"' runway.json | sed 's/.*"projectName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
        if [ -z "$PROJECT_NAME" ]; then
          echo "::error::Could not extract projectName from runway.json"
          exit 1
        fi
        echo "Project name: $PROJECT_NAME"
        echo "project-name=$PROJECT_NAME" >> $GITHUB_OUTPUT

        echo "Generating dependency graph and manifest..."
        lake env ${{ github.workspace }}/_sbs_toolchain/Dress/.lake/build/bin/extract_blueprint graph \
          --build .lake/build \
          $PROJECT_NAME

        # Verify manifest was generated
        if [ -f ".lake/build/dressed/manifest.json" ]; then
          echo "Manifest generated successfully"
        else
          echo "::error::manifest.json not found at .lake/build/dressed/manifest.json"
          exit 1
        fi

    # ========================================
    # STEP 11: Generate site with Runway
    # ========================================
    - name: Generate site with Runway
      id: generate-site
      shell: bash
      run: |
        PROJECT_DIR="${{ inputs.project-directory }}"
        if [ "$PROJECT_DIR" == "." ]; then
          PROJECT_DIR="${{ github.workspace }}"
        else
          PROJECT_DIR="${{ github.workspace }}/${{ inputs.project-directory }}"
        fi

        mkdir -p "$PROJECT_DIR/.lake/build/runway"

        # Create CI-compatible runway config with absolute paths
        echo "Creating runway-ci.json with absolute paths..."

        # Read the original runway.json and create modified version
        # Replace relative assetsDir with absolute path to toolchain assets
        if [ -f "$PROJECT_DIR/runway.json" ]; then
          # Copy original config
          cp "$PROJECT_DIR/runway.json" "$PROJECT_DIR/runway-ci.json"

          # Update assetsDir to absolute path
          sed -i 's|"assetsDir"[[:space:]]*:[[:space:]]*"[^"]*"|"assetsDir": "${{ github.workspace }}/_sbs_toolchain/dress-blueprint-action/assets"|g' "$PROJECT_DIR/runway-ci.json"

          # Update blueprintTexPath to absolute path if it's relative
          sed -i "s|\"blueprintTexPath\"[[:space:]]*:[[:space:]]*\"\([^/]\)|\"blueprintTexPath\": \"$PROJECT_DIR/\1|g" "$PROJECT_DIR/runway-ci.json"

          # Update paperTexPath to absolute path if it's relative
          sed -i "s|\"paperTexPath\"[[:space:]]*:[[:space:]]*\"\([^/]\)|\"paperTexPath\": \"$PROJECT_DIR/\1|g" "$PROJECT_DIR/runway-ci.json"

          echo "Runway config:"
          cat "$PROJECT_DIR/runway-ci.json"
        else
          echo "::error::runway.json not found"
          exit 1
        fi

        echo "Running Runway site generator..."
        cd ${{ github.workspace }}/_sbs_toolchain/Runway && lake exe runway \
          --build-dir "$PROJECT_DIR/.lake/build" \
          --output "$PROJECT_DIR/.lake/build/runway" \
          build \
          "$PROJECT_DIR/runway-ci.json"

        echo "Site generation complete"
        echo "site-path=$PROJECT_DIR/.lake/build/runway" >> $GITHUB_OUTPUT

    # ========================================
    # STEP 12: Generate paper (if configured)
    # ========================================
    - name: Generate paper
      id: generate-paper
      shell: bash
      run: |
        PROJECT_DIR="${{ inputs.project-directory }}"
        if [ "$PROJECT_DIR" == "." ]; then
          PROJECT_DIR="${{ github.workspace }}"
        else
          PROJECT_DIR="${{ github.workspace }}/${{ inputs.project-directory }}"
        fi

        # Check if paperTexPath is configured
        if grep -q '"paperTexPath"' "$PROJECT_DIR/runway.json"; then
          echo "Paper configuration found, generating paper..."
          cd ${{ github.workspace }}/_sbs_toolchain/Runway && lake exe runway \
            --build-dir "$PROJECT_DIR/.lake/build" \
            --output "$PROJECT_DIR/.lake/build/runway" \
            paper \
            "$PROJECT_DIR/runway-ci.json"

          if [ -f "$PROJECT_DIR/.lake/build/runway/paper.pdf" ]; then
            echo "Paper PDF generated successfully"
            echo "pdf-path=$PROJECT_DIR/.lake/build/runway/paper.pdf" >> $GITHUB_OUTPUT
          else
            echo "::warning::Paper PDF not generated"
          fi
        else
          echo "No paperTexPath configured, skipping paper generation"
        fi

    # ========================================
    # STEP 13: Handle DocGen4
    # ========================================
    - name: Handle DocGen4 (docs-static)
      if: inputs.docgen4-mode == 'docs-static'
      shell: bash
      run: |
        PROJECT_DIR="${{ inputs.project-directory }}"
        if [ "$PROJECT_DIR" == "." ]; then
          PROJECT_DIR="${{ github.workspace }}"
        else
          PROJECT_DIR="${{ github.workspace }}/${{ inputs.project-directory }}"
        fi

        # Extract GitHub URL from runway.json to determine repo
        GITHUB_URL=$(grep -o '"githubUrl"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROJECT_DIR/runway.json" | sed 's/.*"githubUrl"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')

        if [ -z "$GITHUB_URL" ]; then
          echo "::warning::Could not extract githubUrl from runway.json, skipping docs-static"
          exit 0
        fi

        echo "Downloading DocGen4 docs from docs-static branch..."
        mkdir -p "$PROJECT_DIR/.lake/build/runway/docs"
        cd "$PROJECT_DIR/.lake/build/runway/docs"
        git init -q
        git remote add origin "$GITHUB_URL"
        git fetch origin docs-static --depth=1 || {
          echo "::warning::docs-static branch not found, skipping DocGen4"
          cd ..
          rm -rf docs
          exit 0
        }
        git checkout FETCH_HEAD
        rm -rf .git
        DOC_COUNT=$(find . -name '*.html' | wc -l)
        echo "Downloaded $DOC_COUNT HTML files from docs-static branch"

    - name: Handle DocGen4 (generate)
      if: inputs.docgen4-mode == 'generate'
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: |
        echo "Generating DocGen4 documentation..."
        lake -R -Kenv=dev build +:docs

        # Copy to runway output
        PROJECT_DIR="${{ inputs.project-directory }}"
        if [ "$PROJECT_DIR" == "." ]; then
          PROJECT_DIR="${{ github.workspace }}"
        else
          PROJECT_DIR="${{ github.workspace }}/${{ inputs.project-directory }}"
        fi

        if [ -d ".lake/build/doc" ]; then
          cp -r .lake/build/doc "$PROJECT_DIR/.lake/build/runway/docs"
          DOC_COUNT=$(find "$PROJECT_DIR/.lake/build/runway/docs" -name '*.html' | wc -l)
          echo "Generated $DOC_COUNT DocGen4 HTML files"
        else
          echo "::warning::DocGen4 output not found at .lake/build/doc"
        fi

    # ========================================
    # STEP 14: Upload Pages artifact
    # ========================================
    - name: Verify site structure
      if: inputs.deploy-pages == 'true'
      shell: bash
      run: |
        PROJECT_DIR="${{ inputs.project-directory }}"
        if [ "$PROJECT_DIR" == "." ]; then
          PROJECT_DIR="${{ github.workspace }}"
        else
          PROJECT_DIR="${{ github.workspace }}/${{ inputs.project-directory }}"
        fi

        echo "Site structure:"
        ls -la "$PROJECT_DIR/.lake/build/runway/"
        echo ""
        echo "Key files:"
        for f in index.html dep_graph.html; do
          if [ -f "$PROJECT_DIR/.lake/build/runway/$f" ]; then
            echo "  [OK] $f"
          else
            echo "  [MISSING] $f"
          fi
        done
        # Optional files (only if paper configured)
        for f in paper.html paper.pdf pdf.html; do
          if [ -f "$PROJECT_DIR/.lake/build/runway/$f" ]; then
            echo "  [OK] $f"
          fi
        done
        echo ""
        echo "Directories:"
        for d in assets docs; do
          if [ -d "$PROJECT_DIR/.lake/build/runway/$d" ]; then
            COUNT=$(find "$PROJECT_DIR/.lake/build/runway/$d" -type f | wc -l)
            echo "  [OK] $d/ ($COUNT files)"
          fi
        done

    - name: Upload Pages artifact
      if: inputs.deploy-pages == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.project-directory == '.' && format('{0}/.lake/build/runway', github.workspace) || format('{0}/{1}/.lake/build/runway', github.workspace, inputs.project-directory) }}
